=== AlejandroLemus516/XML/menu.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
	MidTerm Project
	Author: Alejandro Lemus 
	Date: 10/25/2015
	
	This is the menu.xsd schema file that validates against the greekfood.xml compound document.
	
-->	

<?xml-stylesheet type="text/xsl" href="menu.xsl" ?>

<xs:schema xmlns:xs= "http://www.w3.org/2001/XMLSchema"
		   xmlns= "http://example.com/greekmenu"
		   targetNamespace="http://example.com/greekmenu" 
		   elementFormDefault="qualified" attributeFormDefault="unqualified">
	  
<!--
	Element menuInfo is declared as a complexType with a sequence of title, summary, menu 
	two of these elements are declared as global variables.
	
	vocabulary done in a vietnamise blind design.
-->

<xs:element name="menuInfo">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="menu" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!--
	Element menu is delcared here it is a complexType with a sequence of one child element 
	named menuItems
-->

<xs:element name="menu">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="menuItems" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!--
	Element menuItems is declared here it is a complexType 
	with a sequence child element named menuItem 
	which ouccrs at least once but could be limitless.
-->

<xs:element name="menuItems">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="menuItem" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!--
	menuItem element is declared here.
	It's a complexType element with a sequence
	child element called called menuId which.
	menuItem holds an attribute called course
	that is required.
-->

<xs:element name="menuItem">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="menuId" />
		</xs:sequence>
		<xs:attribute name="course" use="required" />
	</xs:complexType>
</xs:element>


<!-- 
	Declared the price element 
	It's a complexType with 
	an attribute currency that is required.
-->

<xs:element name="price">
</xs:element>

<!--
	Declared a rating element complexType 
	with an attribute called star that is 
	required.
-->

<xs:element name="rating">
	<xs:complexType>
		<xs:simpleContent>
			<xs:extension base="xs:ENTITY">
				<xs:attribute name="star" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:element>
<!--
	Declared a element by the name of menuId 
	it is a complexType with children itemName,
	description, price , and rating.
-->
<xs:element name="menuId">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="itemName" />
			<xs:element ref="description" />
			<xs:element name="price" />
			<xs:element name="rating" />
		</xs:sequence>
		<xs:attribute name="gid" use="required" />
	</xs:complexType>
</xs:element>
<!--
	This is where I declared all my elements globally 
	then referenced them in the complex elements.
-->
<xs:element name="title" type="xs:string" />
<xs:element name="summary" type="xs:string" />
<xs:element name="itemName" type="xs:string" />
<xs:element name="description" type="xs:string" />



<!--
	This is where I declared my simpleTypes 
	custom data types for my xml vocabulary.
-->

<xs:simpleType name="course">
	<xs:restriction base="xs:string">
		<xs:pattern value="[a-z]" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="gid">
	<xs:restriction base="xs:ID">
		<xs:pattern value="GF\d{3}" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="star">
	<xs:restriction base="xs:int">
		<xs:pattern value="[1-4]" />
	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== AlejandroLemus516/XML/greekmenu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	
<!--
	
	MidTerm Project
	Author: Alejandro Lemus 
	Date: 10/25/2015
	
	Files used: menu.xsd
	
-->
<!--
This is my greekmenu.xml vocabulary 

The root element is menuInfo followed by child 
elements called title, summary, and menu.

menu is the parent of menuItems.

menuItems is the parent of menuItem

menuItem has children that contain an attribute called

menuId, description, price, rating.


-->

<?xml-stylesheet type="text/xsl" href="menu.xsl" ?>

<menuInfo xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	
		  schemaLocation="http://example.com/greekmenu menu.xsd">
		  
	<menu>
		<menuItems> 							
			<menuItem course="Entree">
				<menuId gid="GF001">
					<itemName>Giouvetsi</itemName>
					<description>
					<![CDATA[
					Amazingly tasty and tender! Giouvetsi, or youvetsi is a centuries old dish that was traditionally 
					served as a one-pot meal and in the old days. 
					]]>
					</description>
					<price currency="USD">$11.95</price>
					<rating star="3">&#9733; &#9733; &#9733;</rating>
				</menuId>
		  </menuItem>
		  <menuItem course="Entree">
		  		<menuId gid="GF002">
		  			<itemName>Gyros</itemName>
					<description>
					<![CDATA[
					A sandwich made usually of sliced roasted lamb, onion, and tomato on pita bread.
					]]>
					</description>
					<price currency="USD">$9.50</price>
					<rating star="4">&#9733; &#9733; &#9733; &#9733;</rating>
				</menuId>
		</menuItem>	
		<menuItem course="Soup">
			<menuId gid="GF003">
				<itemName>Fasolada</itemName>
				<description>
				<![CDATA[
				Fasolada is an amazing dish which is hardly known outside the borders of Greece. 
				Itâ€™s a tasty soul-soothing bean, carrots and celery soup, which is widely popular in Greece.
				]]>
				</description>
				<price currency="USD">$7.25</price>
				<rating star="2">&#9733; &#9733;</rating>
			</menuId>
		</menuItem>
		<menuItem course="Soup ">
			<menuId gid="GF004">
			   <itemName>Avgolemono</itemName>
			   <description>
			   <![CDATA[
			   A Egg-Lemon soup. The traditional broth is thickened with eggs and falovered with lemon to make a dense,
			   creamy soup with great taste and texture.
		       ]]>
			  </description>
			  <price currency="USD">$8.50</price>
			  <rating star="3">&#9733; &#9733; &#9733;</rating>
			</menuId>
		</menuItem>
		<menuItem course="Appetizer">
			<menuId gid="GF005">
				<itemName>Sliced Feta</itemName>
				<description>
				<![CDATA[
				A 1/2 inch slice of feta cheese on a salad plate. You can it plain or served 
				with a sprinkle of oregano and drizzeled with olive oil. 
				]]>
				</description>
				<price currency="USD">$4.50</price>
				<rating star="2">&#9733; &#9733;</rating>
			</menuId>
		</menuItem>
		<menuItem course="Appetizer">
			<menuId gid="GF006">
				<itemName>Melitzanes Tiganites</itemName>
				<description>
				<![CDATA[
				Eggplant fried to crispy perfection, Served in slices of four could compliment any Entree.
				]]>
				</description>
				<price currency="USD">4.50</price>
				<rating star="1">&#9733;</rating>
			</menuId>
		</menuItem>
		<menuItem course="Dessert">
			<menuId gid="GF007">
				<itemName>Baklava</itemName>
				<description>
				<![CDATA[
				A rich, sweet pastry made of layers of filo filled with chopped nuts and sweetened 
				and held together with syrup or honey.
				]]>
				</description>
				<price currency="USD">$6.25</price>
				<rating star="3">&#9733; &#9733; &#9733;</rating>
		   </menuId>
		</menuItem>
		<menuItem course="Dessert">
			<menuId gid="GF008">
				<itemName>Bougatsa</itemName>
				<description>
				<![CDATA[
				Pastry consisting of either vanilla custard or (salty) cheese filling between layers of phyllo.
				]]>
				</description>
				<price currency="USD">$4.00</price>
				<rating star="4">&#9733; &#9733; &#9733; &#9733;</rating>
		  </menuId>
	    </menuItem>
		</menuItems>
	</menu>
</menuInfo>
